version: 0.2

phases:
  install:
    commands:
      - echo is node.js live?
      - node -v
      - echo is npm live?
      - npm -v
      - echo Angular CLI
      - npm install -g @angular/cli
      - npm install
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      #- ng test --watch=false
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
